---
name: Build - Windows

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

env:
  CMAKE_BUILD_PARALLEL_LEVEL: 2
  MAKEFLAGS: '-j 2'

jobs:
  job:
    name: ${{ matrix.os }}-${{ matrix.buildtype }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2022]
        buildtype: [windows-release]
        include:
          - os: windows-2022
            triplet: x64-windows
            packages: >
              sccache

    steps:

      - name: Restore artifacts and install vcpkg
        id: xyz
        run: |
          $json=Get-Content vcpkg.json -Raw | ConvertFrom-Json
          $vcpkgCommitId=$json.'builtin-baseline'
          Write-Host "vcpkg commit ID: $vcpkgCommitId"
          echo "vcpkgGitCommitId::$vcpkgCommitId" $GITHUB_OUTPUT

      - name: beats
        run: |
          echo "${{ steps.xyz.outputs.vcpkgGitCommitId }}"

      - name: Set Sum
        id: abc
        run: echo "SUM=20" >> $GITHUB_OUTPUT

      - name: Get Sum
	      run: echo "${{ steps.abc.outputs.SUM }}"
